const Fragancias = [
    {id: 1,
        nombre: "Lirios del valle",
        momento: "mañana",
        habitación: "living",
        nivel: "sutil",
        aroma: "floral",       
        descripcion: "Fragancia floral, con notas de bergamota, limón, mandarina y té verde. Una mezcla de son de rosas, iris, lirio, jazmín, musgo, roble, cedro, sándalo y ámbar. El perfume tiene un olor fresco e intenso." 
    },
    {id: 2,
        nombre: "Vainilla Gala",
        momento: "mañana",
        habitación: "living",
        nivel: "normal",
        aroma: "dulce",      
        descripcion: "Dulce especiada. Combina notas de vainilla negra, azúcar tostada y canela."  
    },
    {id: 3,
        nombre: "Jazz Black",
        momento: "mañana",
        habitación: "otros",
        nivel: "sutil",
        aroma: "relajante",      
        descripcion: "Una fragancia floral suave con clavos de olor, bergamota y neroli. Con corazón de jazmín, rosa y flor de azahar. Y unos toques de orquídea de vainilla, sándalo y vetiver."  
    },
    {id: 4,
        nombre: "Instant Karma",
        momento: "tarde",
        habitación: "living",
        nivel: "intenso",
        aroma: "amaderado",     
        descripcion: "Aroma amaderado, floral frutal. Sentirás notas de nardo, musk, maderas y un toque frutal dulce."   
    },
    {id: 5,
        nombre: "Green Garden",
        momento: "tarde",
        habitación: "baño",
        nivel: "alto",
        aroma: "dulce",        
        descripcion: "Una fragancia frutal, fresca y deliciosa. Con una combinación de peras, manzanas, pepinos y más."
    },
    {id: 6,
        nombre: "Orange Bloom",
        momento: "noche",
        habitación: "cocina",
        nivel: "normal",
        aroma: "cítrico",      
        descripcion: "Fragancia oriental cítrica. Con notas de naranjas dulces, sándalo dulce y pimienta especiada."  
    },
    {id: 7,
        nombre: "Irish Coffee",
        momento: "noche",
        habitación: "living",
        nivel: "intenso",
        aroma: "relajante",     
        descripcion: "Fragancia muy gourmet, exquisita, con notas de chocolate, cacao, vanille dolce y café."   
    },
    {id: 8,
        nombre: "Vanity F",
        momento: "noche",
        habitación: "living",
        nivel: "alto",
        aroma: "amaderado",    
        descripcion: "Esta fragancia amaderada tiene notas de pomelo, menta, mandarina roja, rosa, canela, notas especiadas. Aroma a cuero, pachuli e hindú."    
    },
    {id: 9,
        nombre: "Tila Mint",
        momento: "relax",
        habitación: "living",
        nivel: "sutil",
        aroma: "relajante",   
        descripcion: "Un aroma floral herbal fresco, relajante, que mezcla las notas de tilo y lavanda, con unas pequeñas notas de menta."     
    },
    {id: 10,
        nombre: "Floral Tea",
        momento: "relax",
        habitación: "living",
        nivel: "intermedio",
        aroma: "relajante",        
        descripcion: "Aroma floral cítrico, con una mezcla de tilo y un delicado aroma a té verde."
    },
    {id: 11,
        nombre: "Bouquet de Fresias",
        momento: "mañana",
        habitación: "living",
        nivel: "alto",
        aroma: "floral",        
        descripcion: "Aroma floral, con toques de fresias frescas con la suavidad del algodón. Fragancia muy delicada."
    },
    {id: 12,
        nombre: "Vainana",
        momento: "tarde",
        habitación: "living",
        nivel: "sutil",
        aroma: "dulce",        
        descripcion: "Una nueva combinación perfecta de vainillas tostadas con notas frutales de ananá."
    },
    {id: 13,
        nombre: "Pink Touch",
        momento: "mañana",
        habitación: "cocina",
        nivel: "normal",
        aroma: "cítrico",        
        descripcion: "Fragancia cítrica con el pomelo rosado como nota principal. También sentirás aromas a mandarina y limón."
    },
    {id: 14,
        nombre: "Bergamota Glow",
        momento: "mañana",
        habitación: "cocina",
        nivel: "sutil",
        aroma: "cítrico",    
        descripcion: "Aroma floral verde frutada que combina notas de bergamota, limón, artemisa y melón. Perfecto acorde con ámbar, cedro, sándalo y un toque exótico de semillas de Tonka."    
    },
    {id: 15,
        nombre: "Tropic",
        momento: "tarde",
        habitación: "baño",
        nivel: "sutil",
        aroma: "dulce",       
        descripcion: "Fragancia floral frutal. Con notas de frutas tropicales como el mango, la papaya y el maracuyá." 
    },
    {id: 16,
        nombre: "Aqua Meel",
        momento: "mañana",
        habitación: "dormitorio",
        nivel: "normal",
        aroma: "floral",      
        descripcion: "Amaderada floral frutal. Con notas de nardo, musk y maderas con un toque frutal dulce."  
    },
    {id: 17,
        nombre: "Amalfi Glam",
        momento: "tarde",
        habitación: "living",
        nivel: "intermedio",
        aroma: "floral",      
        descripcion: "Esta fragancia floral frutal tiene notas de limón de amalfi y lima. También sentirás aromas como manzana, peonía, almendras, flor de manzano, almizcle y cedro de Virginia."  
    },
    {id: 18,
        nombre: "Cupcake",
        momento: "tarde",
        habitación: "baño",
        nivel: "alto",
        aroma: "dulce",        
        descripcion: "Aroma gourmet dulce con notas de vainilla, caramel y vainilla tostada."
    },
    {id: 19,
        nombre: "Delicious Chic",
        momento: "tarde",
        habitación: "cocina",
        nivel: "sutil",
        aroma: "dulce",        
        descripcion: "Frutal dulce, con notas de cerezas, moras, frutillas y toques de vainilla tostada."
    },
    {id: 20,
        nombre: "La vida es Galas",
        momento: "mañana",
        habitación: "cocina",
        nivel: "normal",
        aroma: "cítrico",      
        descripcion: "Una nueva fragancia similar a “La vida es bella” con notas afrutadas, donde se puede distinguir la grosella negra y la pera. Dulce."  
    },    

    {id: 21,
        nombre: "Aqua Meel",
        momento: "tarde",
        habitación: "living",
        nivel: "sutil",
        aroma: "amaderado",      
        descripcion: "Amaderada floral frutal. Con notas de nardo, musk y maderas con un toque frutal dulce."  
    },
    {id: 22,
        nombre: "Vervena Glow",
        momento: "mañana",
        habitación: "baño",
        nivel: "intermedio",
        aroma: "cítrico",       
        descripcion: "" 
    },
    {id: 23,
        nombre: "Aqua Meel",
        momento: "noche",
        habitación: "living",
        nivel: "intermedio",
        aroma: "amaderado",    
        descripcion: "Amaderada floral frutal. Con notas de nardo, musk y maderas con un toque frutal dulce."    
    },
    {id: 24,
        nombre: "Vainilla Gala",
        momento: "tarde",
        habitación: "dormitorio",
        nivel: "normal",
        aroma: "relajante",    
        descripcion: "Dulce especiada. Combina notas de vainilla negra, azúcar tostada y canela."    
    },
    {id: 25,
        nombre: "Pink Touch",
        momento: "mañana",
        habitación: "baño",
        nivel: "alto",
        aroma: "cítrico",    
        descripcion: "Fragancia cítrica con el pomelo rosado como nota principal. También sentirás aromas a mandarina y limón."    
    },
    {id: 26,
        nombre: "Tila Mint",
        momento: "tarde",
        habitación: "dormitorio",
        nivel: "alto",
        aroma: "relajante",       
        descripcion: "Un aroma floral herbal fresco, relajante, que mezcla las notas de tilo y lavanda, con unas pequeñas notas de menta." 
    },
    {id: 27,
        nombre: "Bouquet de fresias",
        momento: "tarde",
        habitación: "dormitorio",
        nivel: "intenso",
        aroma: "floral",     
        descripcion: "Aroma floral, con toques de fresias frescas con la suavidad del algodón. Fragancia muy delicada."   
    },
    {id: 28,
        nombre: "Vanity F",
        momento: "noche",
        habitación: "dormitorio",
        nivel: "intenso",
        aroma: "dulce",       
        descripcion: "Esta fragancia amaderada tiene notas de pomelo, menta, mandarina roja, rosa, canela, notas especiadas. Aroma a cuero, pachuli e hindú." 
    },
    {id: 29,
        nombre: "Pink Touch",
        momento: "tarde",
        habitación: "baño",
        nivel: "intenso",
        aroma: "cítrico",      
        descripcion: "Fragancia cítrica con el pomelo rosado como nota principal. También sentirás aromas a mandarina y limón."  
    }    
]

export default Fragancias;