const Fragancias = [
    {id: 1,
        nombre: "Lirios del valle",
        momento: "mañana",
        habitación: "living",
        nivel: "sutil",
        aroma: "floral",        
    },
    {id: 2,
        nombre: "Vainilla Gala",
        momento: "mañana",
        habitación: "living",
        nivel: "normal",
        aroma: "frutal",        
    },
    {id: 3,
        nombre: "Jazz Black",
        momento: "mañana",
        habitación: "otros espacios",
        nivel: "sutil",
        aroma: "relajante",        
    },
    {id: 4,
        nombre: "Instant Karma",
        momento: "tarde",
        habitación: "living",
        nivel: "intenso",
        aroma: "amaderado",        
    },
    {id: 5,
        nombre: "Green Garden",
        momento: "tarde",
        habitación: "baño",
        nivel: "alto",
        aroma: "frutal",        
    },
    {id: 6,
        nombre: "Orange Bloom",
        momento: "noche",
        habitación: "cocina",
        nivel: "normal",
        aroma: "cítrico",        
    },
    {id: 7,
        nombre: "Irish Coffee",
        momento: "cena",
        habitación: "living",
        nivel: "intenso",
        aroma: "relajante",        
    },
    {id: 8,
        nombre: "Vanity F",
        momento: "cena",
        habitación: "living",
        nivel: "alto",
        aroma: "amaderado",        
    },
    {id: 9,
        nombre: "Tila Mint",
        momento: "para relajarme",
        habitación: "living",
        nivel: "sutil",
        aroma: "relajante",        
    },
    {id: 10,
        nombre: "Floral Tea",
        momento: "para relajarme",
        habitación: "living",
        nivel: "intermedio",
        aroma: "relajante",        
    },
    {id: 11,
        nombre: "Bouquet Fresias",
        momento: "mañana",
        habitación: "living",
        nivel: "alto",
        aroma: "floral",        
    },
    {id: 12,
        nombre: "Vainana",
        momento: "tarde",
        habitación: "living",
        nivel: "sutil",
        aroma: "frutal",        
    },
    {id: 13,
        nombre: "Pink Touch",
        momento: "mañana",
        habitación: "cocina",
        nivel: "normal",
        aroma: "cítrico",        
    },
    {id: 14,
        nombre: "Bergamota Glow",
        momento: "mañana",
        habitación: "cocina",
        nivel: "sutil",
        aroma: "cítrico",        
    },
    {id: 15,
        nombre: "Tropic",
        momento: "tarde",
        habitación: "baño",
        nivel: "sutil",
        aroma: "frutal",        
    },
    {id: 16,
        nombre: "Aqua Meel",
        momento: "mañana",
        habitación: "dormitorio",
        nivel: "normal",
        aroma: "floral",        
    },
    {id: 17,
        nombre: "Amalfi Glam",
        momento: "tarde",
        habitación: "living",
        nivel: "intermedio",
        aroma: "floral",        
    },
    {id: 18,
        nombre: "Cupcake",
        momento: "tarde",
        habitación: "baño",
        nivel: "alto",
        aroma: "frutal",        
    },
    {id: 19,
        nombre: "Delicious Chic",
        momento: "tarde",
        habitación: "cocina",
        nivel: "sutil",
        aroma: "frutal",        
    },
    {id: 20,
        nombre: "La vida es Galas",
        momento: "mañana",
        habitación: "cocina",
        nivel: "normal",
        aroma: "cítrico",        
    },
    {id: 21,
        nombre: "Lirios del valle",
        momento: "mañana",
        habitación: "living",
        nivel: "normal",
        aroma: "floral",        
    },
    {id: 22,
        nombre: "Vainilla Gala",
        momento: "mañana",
        habitación: "dormitorio",
        nivel: "normal",
        aroma: "frutal",        
    },
    {id: 23,
        nombre: "Instant Karma",
        momento: "noche",
        habitación: "dormitorio",
        nivel: "intenso",
        aroma: "amaderado",        
    },
    {id: 24,
        nombre: "Green Garden",
        momento: "tarde",
        habitación: "otros espacios",
        nivel: "alto",
        aroma: "frutal",        
    },
    {id: 25,
        nombre: "Orange Bloom",
        momento: "noche",
        habitación: "otros espacios",
        nivel: "normal",
        aroma: "cítrico",        
    },
    {id: 26,
        nombre: "Irish Coffee",
        momento: "cena",
        habitación: "cocina",
        nivel: "intenso",
        aroma: "relajante",        
    },
    {id: 27,
        nombre: "Vanity F",
        momento: "cena",
        habitación: "dormitorio",
        nivel: "alto",
        aroma: "amaderado",        
    },
    {id: 28,
        nombre: "Tila Mint",
        momento: "para relajarme",
        habitación: "dormitorio",
        nivel: "sutil",
        aroma: "relajante",        
    },
    {id: 29,
        nombre: "Bouquet Fresias",
        momento: "tarde",
        habitación: "living",
        nivel: "alto",
        aroma: "floral",        
    },
    {id: 30,
        nombre: "Bouquet Fresias",
        momento: "noche",
        habitación: "living",
        nivel: "alto",
        aroma: "floral",        
    },
    {id: 31,
        nombre: "Floral Tea",
        momento: "para relajarme",
        habitación: "dormitorio",
        nivel: "intermedio",
        aroma: "relajante",        
    },
    {id: 32,
        nombre: "Floral Tea",
        momento: "para relajarme",
        habitación: "otros espacios",
        nivel: "intermedio",
        aroma: "relajante",        
    },
    {id: 33,
        nombre: "Pink Touch",
        momento: "tarde",
        habitación: "baño",
        nivel: "normal",
        aroma: "cítrico",        
    },
    {id: 34,
        nombre: "Pink Touch",
        momento: "noche",
        habitación: "cocina",
        nivel: "normal",
        aroma: "cítrico",        
    },
    {id: 35,
        nombre: "Bergamota Glow",
        momento: "noche",
        habitación: "cocina",
        nivel: "sutil",
        aroma: "cítrico",        
    },
    {id: 36,
        nombre: "Tropic",
        momento: "tarde",
        habitación: "cocina",
        nivel: "sutil",
        aroma: "frutal",        
    },
    {id: 37,
        nombre: "Aqua Meel",
        momento: "noche",
        habitación: "dormitorio",
        nivel: "normal",
        aroma: "amaderado",        
    },
    {id: 38,
        nombre: "Aqua Meel",
        momento: "cena",
        habitación: "dormitorio",
        nivel: "normal",
        aroma: "floral",        
    },
    {id: 39,
        nombre: "Amalfi Glam",
        momento: "noche",
        habitación: "cocina",
        nivel: "intermedio",
        aroma: "floral",        
    },
    {id: 40,
        nombre: "Amalfi Glam",
        momento: "tarde",
        habitación: "dormitorio",
        nivel: "intermedio",
        aroma: "floral",        
    },
    {id: 41,
        nombre: "Amalfi Glam",
        momento: "tarde",
        habitación: "otros espacios",
        nivel: "intermedio",
        aroma: "floral",        
    },
    {id: 42,
        nombre: "Cupcake",
        momento: "tarde",
        habitación: "dormitorio",
        nivel: "alto",
        aroma: "frutal",        
    },
    {id: 43,
        nombre: "Delicious Chic",
        momento: "noche",
        habitación: "dormitorio",
        nivel: "sutil",
        aroma: "frutal",        
    },
    {id: 44,
        nombre: "La vida es Galas",
        momento: "noche",
        habitación: "dormitorio",
        nivel: "normal",
        aroma: "cítrico",        
    }
]

export default Fragancias;