const productos = [
    {id: 1,
        nombre: "Vela de soja Milo",
        categoria: "Velas",
        descripcion: "Vela de soja",
        duracion:12,
        gramos: 100,
        imagen: "",},
    {id: 2,
        nombre: "Difusor de vidrio",
        categoria: "Difusores",
        descripcion: "Difusor de vidrio con varillas",
        duracion:12,
        gramos: 100,
        imagen: "",},
    {id: 3,
        nombre: "Perfumina",
        categoria: "Perfuminas",
        descripcion: "Perfumina nene/nena/unisex",
        duracion:12,
        gramos: 100,
        imagen: "",},
    {id: 4,
        nombre: "Refill",
        categoria: "Refill",
        descripcion: "Refill",
        duracion:12,
        gramos: 100,
        imagen: "",},
    {id: 5,
        nombre: "Hornito",
        categoria: "Hornitos",
        descripcion: "Hornito",
        duracion:12,
        gramos: 100,
        imagen: "",}
];

export default productos;