const productos = [
    {id: 1,        
        nombre: "Perfumina Rise",
        categoria: "Perfuminas",
        descripcionCard: "Perfumina 250ml/500ml",
        descripcion: "Perfume de ambientes y textil infantil con gatillo o válvula spray según stock. Presentación bebe para nene, nena y unisex.",
        medida: "15cm de alto x 8cm de ancho",
        duracion: "según frecuencia de uso.",
        cantidad: "Presentación 250 ml y 500 ml.",
        destacado: false,
        imagen: "/img/fotos-rectangulares/perfumina-rise-shine.png",},    
    {id: 2,
        nombre: "Kit Babilonia",
        categoria: "Hornitos",
        descripcionCard: "Horno cerámico artesanal",
        descripcion: "Horno cerámico ARTESANAL en forma de gota + 3 velitas de noche. 3 barras de esencia solida wax melts o 18 bombones surtidos de aromas (formas varias) colores: negro, blanco grabado de hojitas, natural, verde aqua y mas. Consultar stock disponibles",
        medida: "15cm de alto x 10cm de ancho",        
        cantidad: "1",
        destacado: false,
        imagen: "/img/fotos-rectangulares/horno-babilonia.png",},
    {id: 3,
        nombre: "Vela Honey",
        categoria: "Velas",
        descripcionCard: "Vela de soja 270g",
        descripcion: "Vela de cera de soja vegetal. Perfumada con aceites puros. Envase 100% reutilizable de vidrio espejado en tono miel tornasol traslucido.",
        medida: "12cm de alto x 7cm de ancho",
        duracion: "85 hrs aprox.",
        cantidad: "270g",
        destacado: true,
        imagen: "/img/fotos-rectangulares/vela-honey.png",},
    {id: 4,
        nombre: "Vela Liam",
        categoria: "Velas",
        descripcionCard: "Vela de soja 300g",
        descripcion: "Vela de cera de soja vegetal. Perfumada con aceites puros. Envase 100% reutilizable de aluminio anodizado de fabricación nacional y tapa tramada. En metal brilloso o satinado. Colores disponibles: > HABANO brillante y satinado. > CHAMPAGNE brillante. Pabilo de algodón encerado.",
        medida: "8cm de ancho x 7cm de alto.",
        duracion: "más de 85 hrs.",
        cantidad: "300g",
        destacado: true,
        imagen: "/img/fotos-rectangulares/vela-liam.png",},
    {id: 5,
        nombre: "Difusor Monterrey",
        categoria: "Difusores",
        descripcionCard: "Difusor 500ml/250ml",
        descripcion: "Difusor con varillas de ratán negro, presentado en envase de vidrio cromado color plomo con tapa difusora de madera negra. Envase 100% reutilizable. ",
        medida: "13 cm de alto,  8 cm de diámetro.",
        duracion: "1460 hrs aprox.",
        cantidad: "500 ml/250 ml",
        destacado: true,
        imagen: "/img/fotos-rectangulares/difusor-monterrey.png",},
    {id: 6,
        nombre: "Vela Patagonia",
        categoria: "Velas",
        descripcionCard: "Vela de soja 210g",
        descripcion: "Vela de cera de soja vegetal. Perfumada con aceites puros. Envase 100% reutilizable de vidrio facetado y pabilo de algodón.",
        medida: "7,2 cm de ancho x 13 cm de alto / 8.5 cm de ancho x 7 cm de alto",
        duracion: "más de 70 hrs.",
        cantidad: "210g",
        destacado: true,
        imagen: "/img/fotos-rectangulares/vela-patagonia.png",},
    {id: 7,
        nombre: "Vela Arcoiris",
        categoria: "Velas",
        descripcionCard: "Vela de molde",
        descripcion: "Vela de molde con forma de arcoíris. Decorada con glitter (opcional) y de colores. Perfumada en flores blancas, fresias, jazmín, chicle, vainilla o tropical. Pueden ser surtidos. Mínimo de compra 5 unidades por aroma.",
        medida: "12cm alto",
        duracion: "según uso.",
        cantidad: "250g",        
        destacado: false,
        imagen: "/img/fotos-rectangulares/vela-arcoiris-XL.png",},
       
    {id: 8,
        nombre: "Souvenir Shots",
        categoria: "Velas",
        descripcionCard: "Vela de soja 100g",
        descripcion: "Vela de cera de soja. Envase de vidrio. Perfumada con flores blancas, fresias, jazmín, chicle, vainilla y cotton. 10 unidades por aroma. Incluye calco con nombre y diseño. Mínimo de compra 20 unidades, opcional tarjeta (consultar valor).",
        medida: "6cm de alto x 4cm de ancho",
        duracion: "30hs",
        cantidad: "100g",
        destacado: false,
        imagen: "/img/fotos-rectangulares/souvenir-shot.png",},
    {id: 9,
        nombre: "Souvenirs Frasquis",
        categoria: "Velas",
        descripcionCard: "Vela de soja 100g",
        descripcion: "Vela de cera de soja en envase de vidrio con tapa. Puede decorarse con cintas o moños, más una etiqueta. Diseño incluído. Perfumada en flores blancas, fresias, jazmín, chicle, vainilla y cotton. 5 unidades por aroma. Consultar variedad.",
        medida: "6cm de alto x 4cm de ancho",
        duracion: "30hs",
        cantidad: "100g aprox.",
        destacado: false,
        imagen: "/img/fotos-rectangulares/souvenir-frasquitos.png",},
    {id: 10,
        nombre: "Vela Cupcake",
        categoria: "Velas",
        descripcionCard: "Vela de soja 300g",
        descripcion: "Vela de cera de soja vegetal. TEMATICA CUPCAKE. Perfumada con aceites. DECORADA CON GLITTER Y PURPURINAS. Envase de vidrio 100% reutilizable.",
        medida: "8cm de ancho x 7,5cm de alto.",
        duracion: "más de 85 hrs.",
        cantidad: "300g",
        destacado: false,
        imagen: "/img/fotos-rectangulares/vela-cupcake.png",},
    {id: 11,
        nombre: "Vela Nube",
        categoria: "Velas",
        descripcionCard: "Vela de soja x3 unidades",
        descripcion: "Vela de soja de molde en forma de nube. Decorada con glitter y esfume de colores: celeste y blanco | Cereza y blanco | Turquesa y blanco | Lila/Magenta y blanco. Perfumada. Debe colocarse siempre sobre una base. Ideal Souvenirs.",
        medida: "7 cm ancho, 4 cm de alto",
        duracion: "12 hrs aprox.",
        cantidad: "pack de 3 unidades.",
        destacado: false,
        imagen: "/img/fotos-rectangulares/vela-nube.png",},
    {id: 12,        
        nombre: "KIT Velas Liam",
        categoria: "Velas",
        descripcionCard: "Vela de soja 300g",
        descripcion: 'VELA LIAM habano. Edición “amor y paz”, vinilo glitter plata / vinilo oro / vinilo blanco. VELA LIAM dorada, vinilo blanco.',
        medida: "7cm de alto. 8cm de ancho.",
        duracion: "más de 85 hrs aprox.",
        cantidad: "300g",
        destacado: false,
        imagen: "/img/fotos-rectangulares/kit-velas-liam.png",},
    {id: 13,
        nombre: "Vela Santa Dominga",
        categoria: "Velas",
        descripcionCard: "Vela de soja 260g",
        descripcion: "Vela de cera de soja vegetal. Perfumada con aceites. Envase de vidrio  100% reutilizable.",
        medida: "8 cm de ancho x 7,5cm de alto.",
        duracion: "más de 85 hrs.",
        cantidad: "260g",
        destacado: false,
        imagen: "/img/fotos-rectangulares/vela-santa-dominga.png",},
    {id: 14,
        nombre: "Perfumina Moon",
        categoria: "Perfuminas",
        descripcionCard: "Perfumina 250ml/500ml",
        descripcion: "Perfume de ambientes y textil infantil con gatillo o válvula spray según stock.",
        medida: "15cm de alto x 8cm de ancho",
        duracion: "según frecuencia de uso",
        cantidad: "250 ml/500 ml",
        destacado: false,
        imagen: "/img/fotos-rectangulares/perfumina-moon.png",},    
    {id: 15,
        nombre: "Difusor Honey",
        categoria: "Difusores",
        descripcionCard: "Difusor de aroma 270g",
        descripcion: "Difusor de aroma. Envase 100% reutilizable de vidrio espejado en tono miel tornasol translúcido. 6 varillas rattan color natural",
        medida: "12cm alto x 7cm  de ancho ( sin varillas.)",
        duracion: "1460 hrs aprox.",
        cantidad: "270g",        
        destacado: false,
        imagen: "/img/fotos-rectangulares/difusor-honey.png",},
    {id: 16,
        nombre: "Difusor Little Galas",
        categoria: "Difusores",
        descripcionCard: "Difusor de aroma 250ml",
        descripcion: "Difusor de aroma. Envase PET. 6 varillas rattan color natural",
        medida: "13cm alto x 7cm  de ancho ( sin varillas.)",
        duracion: "1460 hrs aprox.",
        cantidad: "250 ml.",        
        destacado: false,
        imagen: "/img/fotos-rectangulares/difusor-little-galas.png",},
    {id: 17,
        nombre: "Vela cónica",
        categoria: "Velas",
        descripcionCard: "Vela de soja 1kg",
        descripcion: "Vela vertida a mano realizada con aceites de perfumería fina. Envase de vidrio premium.",
        medida: "17cm de alto x 14cm de ancho",
        duracion: "más de 100 hrs.",
        cantidad: "1kg",
        destacado: false,
        imagen: "/img/fotos-rectangulares/vela-conica.png",},
    {id: 18,
        nombre: "Refill de velas",
        categoria: "Refill",
        descripcionCard: "Refill vela de soja 250ml",
        descripcion: "Vela de cera de soja en envase apto microondas y baño maría. Contiene 2 pabilos listos para usar.",
        medida: "6cm de alto x 7cm de ancho con tapa.",
        duracion: "80 hrs.",
        cantidad: "250ml",
        destacado: false,
        imagen: "/img/fotos-rectangulares/refil-velas.png",},
    {id: 19,
        nombre: "Vela Bombe Solar",
        categoria: "Velas",
        descripcionCard: "Vela de soja 700g",
        descripcion: "Vela vertida a mano realizada con aceites de perfumería fina. Envase de vidrio premium. Con tapa de acero anodizado opcional.",
        medida: "17cm de alto x 13cm de ancho",
        duracion: "80 hrs.",
        cantidad: "700g",
        destacado: false,
        imagen: "/img/fotos-rectangulares/vela-bombe-solar.png",},
    {id: 20,
        nombre: "Difusor Dubai",
        categoria: "Difusores",
        descripcionCard: "Difusor 250ml",
        descripcion: "Difusor de vidrio. Tapa de madera y varillas ratan por 6 unidades.",
        medida: "14.5cm de alto x 7cm de ancho",
        duracion: "2 meses aprox.",
        cantidad: "250ml",
        destacado: false,
        imagen: "/img/fotos-rectangulares/difusor-dubai.png",},
    {id: 21,
        nombre: "Difusor Lili",
        categoria: "Difusores",
        descripcionCard: "Difusor 40ml",
        descripcion: "Difusor de vidrio. 4 caras. Tapón corcho. 4 varillas rattan natural.",
        medida: "8cm de ancho x 7,5cm de alto.",
        duracion: "de 3 a 4 semanas.",
        cantidad: "40ml",
        destacado: false,
        imagen: "/img/fotos-rectangulares/difusor-lili.png",},
    {id: 22,
        nombre: "Vela Lotus",
        categoria: "Velas",
        descripcionCard: "Vela de soja 250g",
        descripcion: "Vela de soja vertida a mano en envase pintado color aqua.  Vinilo dorado diseño flor de loto.",
        medida: "8cm de alto x 8cm de ancho.",
        duracion: "85 hrs. aprox.",
        cantidad: "250g",
        destacado: false,
        imagen: "/img/fotos-rectangulares/vela-lotus.png",},
    {id: 23,
        nombre: "Vela Cubo",
        categoria: "Velas",
        descripcionCard: "Vela de soja 300g",
        descripcion: "Vela de cera de soja vertida a mano. Doble pabilo. Envase Vidrio grueso premium. Semi esmerilado.",
        medida: "8cm de alto x 8cm de ancho.",
        duracion: "90 hrs. aprox.",
        cantidad: "300g",
        destacado: false,
        imagen: "/img/fotos-rectangulares/vela-cubo.png",},
    {id: 24,
        nombre: "Vela Lets Your Soul Shine",
        categoria: "Velas",
        descripcionCard: "Vela de soja 280g",
        descripcion: "Vela de cera de soja vegetal. Perfumada con aceites puros de perfumería fina.  Envase 100% reutilizable de vidrio y pabilo de algodón.",
        medida: "8cm de ancho x 7,5cm de alto.",
        duracion: "más de 85 hrs.",
        cantidad: "280g",
        destacado: false,
        imagen: "/img/fotos-rectangulares/lets-your-soul-shine.png",},
                                         
];

export default productos;